networks:
  proxy_sql-network:
    external: true
services:
  menu-service:
    image: nginx:alpine
    container_name: hq-menu
    hostname: hq-menu
    networks:
      - proxy_sql-network
    volumes:
      - /src/menu/web:/usr/share/nginx/html:ro
    restart: unless-stopped
